/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PanelRouteImport } from './routes/_panel'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PanelHomeRouteImport } from './routes/_panel/home'
import { Route as PanelTonapiApiKeysRouteImport } from './routes/_panel/tonapi/api-keys'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelRoute = PanelRouteImport.update({
  id: '/_panel',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelHomeRoute = PanelHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => PanelRoute,
} as any)
const PanelTonapiApiKeysRoute = PanelTonapiApiKeysRouteImport.update({
  id: '/tonapi/api-keys',
  path: '/tonapi/api-keys',
  getParentRoute: () => PanelRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/home': typeof PanelHomeRoute
  '/tonapi/api-keys': typeof PanelTonapiApiKeysRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/home': typeof PanelHomeRoute
  '/tonapi/api-keys': typeof PanelTonapiApiKeysRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_panel': typeof PanelRouteWithChildren
  '/login': typeof LoginRoute
  '/_panel/home': typeof PanelHomeRoute
  '/_panel/tonapi/api-keys': typeof PanelTonapiApiKeysRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/home' | '/tonapi/api-keys'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/home' | '/tonapi/api-keys'
  id:
    | '__root__'
    | '/'
    | '/_panel'
    | '/login'
    | '/_panel/home'
    | '/_panel/tonapi/api-keys'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PanelRoute: typeof PanelRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_panel': {
      id: '/_panel'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_panel/home': {
      id: '/_panel/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof PanelHomeRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/tonapi/api-keys': {
      id: '/_panel/tonapi/api-keys'
      path: '/tonapi/api-keys'
      fullPath: '/tonapi/api-keys'
      preLoaderRoute: typeof PanelTonapiApiKeysRouteImport
      parentRoute: typeof PanelRoute
    }
  }
}

interface PanelRouteChildren {
  PanelHomeRoute: typeof PanelHomeRoute
  PanelTonapiApiKeysRoute: typeof PanelTonapiApiKeysRoute
}

const PanelRouteChildren: PanelRouteChildren = {
  PanelHomeRoute: PanelHomeRoute,
  PanelTonapiApiKeysRoute: PanelTonapiApiKeysRoute,
}

const PanelRouteWithChildren = PanelRoute._addFileChildren(PanelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PanelRoute: PanelRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
