services:
  rabbitmq:
    image: rabbitmq:3.13
    restart: always
    expose:
      - "5672"
    environment:
      RABBITMQ_DEFAULT_USER: ${FRAG_AMQP_USER}
      RABBITMQ_DEFAULT_PASS: ${FRAG_AMQP_PWD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - dokploy-network

  db:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_DB=${FRAG_POSTGRES_DATABASE}
      - POSTGRES_USER=${FRAG_POSTGRES_USER}
      - POSTGRES_PASSWORD=${FRAG_POSTGRES_PWD}
      - PGPORT=${FRAG_POSTGRES_PORT}
    ports:
      - ${FRAG_POSTGRES_PORT}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - dokploy-network

  app:
    build: .
    command: sh -c "uv run task pre_deploy && exec uv run uvicorn src.app:app --host 0.0.0.0 --port 8000"
    restart: always
    depends_on:
      - db
    expose:
      - "8000"
    volumes:
      - ${FRAG_SESSION_PATH}:/app/${FRAG_FRAGMENT_SESSION_PATH}
    networks:
      - dokploy-network
    env_file:
      - .env
  #
  # worker:
  #   build: .
  #   command: uv run taskiq worker -w 1 src.worker.run:broker
  #   depends_on:
  #     - db
  #     - rabbitmq
  #   networks:
  #     - dokploy-network
  #   env_file:
  #     - .env


volumes:
  db_data:
  rabbitmq_data:

networks:
  dokploy-network:
    external: true
