services:
  db:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_DB=${FRAG_POSTGRES_DATABASE}
      - POSTGRES_USER=${FRAG_POSTGRES_USER}
      - POSTGRES_PASSWORD=${FRAG_POSTGRES_PWD}
      - PGPORT=${FRAG_POSTGRES_PORT}
    ports:
      - ${FRAG_POSTGRES_PORT}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - dokploy-network

  app:
    build: .
    restart: always
    depends_on:
      - db
    expose:
      - "8000"
    volumes:
      - ${FRAG_SESSION_PATH}:/app/${FRAG_FRAGMENT_SESSION_PATH}
    networks:
      - dokploy-network
    env_file:
      - .env
    labels:
      - "traefik.docker.network=dokploy-network"  # Tell Traefik which network to use

volumes:
  db_data:

networks:
  dokploy-network:
    external: true
