"""fix_ton_trans_id_miss

Revision ID: ced401d0ebc9
Revises: 5cd172428f8f
Create Date: 2026-06-20 09:40:06.817512

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ced401d0ebc9"
down_revision: str | Sequence[str] | None = "5cd172428f8f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ton_transactions",
        sa.Column("nano_amount", sa.BigInteger(), nullable=False),
        sa.Column("hash", sa.String(length=64), nullable=True),
        sa.Column("message_hash", sa.String(length=64), nullable=True),
        sa.Column("from_address", sa.String(length=100), nullable=False),
        sa.Column("to_address", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ton_transactions_created_at"),
        "ton_transactions",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ton_transactions_hash"), "ton_transactions", ["hash"], unique=True
    )
    op.create_index(
        op.f("ix_ton_transactions_message_hash"),
        "ton_transactions",
        ["message_hash"],
        unique=True,
    )
    op.drop_index(
        op.f("ix_fragment_transactions_created_at"), table_name="fragment_transactions"
    )
    op.drop_table("fragment_transactions")
    op.add_column("deposits", sa.Column("ton_transaction_id", sa.Uuid(), nullable=True))
    op.drop_index(op.f("ix_payments_created_at"), table_name="deposits")
    op.drop_constraint(op.f("payments_transaction_id_key"), "deposits", type_="unique")
    op.create_index(
        op.f("ix_deposits_created_at"), "deposits", ["created_at"], unique=False
    )
    op.create_unique_constraint(None, "deposits", ["ton_transaction_id"])
    op.drop_constraint(
        op.f("payments_transaction_id_fkey"), "deposits", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "deposits", "ton_transactions", ["ton_transaction_id"], ["id"]
    )
    op.drop_column("deposits", "transaction_id")
    op.add_column("transactions", sa.Column("user_id", sa.BigInteger(), nullable=False))
    op.add_column("transactions", sa.Column("amount", sa.Float(), nullable=False))
    op.add_column("transactions", sa.Column("recipient", sa.String(), nullable=False))
    op.add_column(
        "transactions", sa.Column("recipient_username", sa.String(), nullable=False)
    )
    op.add_column(
        "transactions", sa.Column("ton_transaction_id", sa.Uuid(), nullable=False)
    )
    op.add_column(
        "transactions",
        sa.Column(
            "reason",
            sa.Enum("premium", "stars", name="transactionreason", native_enum=False),
            nullable=False,
        ),
    )
    op.add_column(
        "transactions", sa.Column("stars_amount", sa.Integer(), nullable=True)
    )
    op.add_column(
        "transactions", sa.Column("premium_months", sa.Integer(), nullable=True)
    )
    op.drop_index(op.f("ix_transactions_hash"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_message_hash"), table_name="transactions")
    op.create_unique_constraint(None, "transactions", ["ton_transaction_id"])
    op.create_foreign_key(None, "transactions", "users", ["user_id"], ["id"])
    op.create_foreign_key(
        None, "transactions", "ton_transactions", ["ton_transaction_id"], ["id"]
    )
    op.drop_column("transactions", "from_address")
    op.drop_column("transactions", "nano_amount")
    op.drop_column("transactions", "hash")
    op.drop_column("transactions", "to_address")
    op.drop_column("transactions", "message_hash")
    # ### end Alembic commands ###


# def downgrade() -> None:
#     """Downgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.add_column(
#         "transactions",
#         sa.Column(
#             "message_hash", sa.VARCHAR(length=64), autoincrement=False, nullable=True
#         ),
#     )
#     op.add_column(
#         "transactions",
#         sa.Column(
#             "to_address", sa.VARCHAR(length=100), autoincrement=False, nullable=False
#         ),
#     )
#     op.add_column(
#         "transactions",
#         sa.Column("hash", sa.VARCHAR(length=64), autoincrement=False, nullable=True),
#     )
#     op.add_column(
#         "transactions",
#         sa.Column("nano_amount", sa.BIGINT(), autoincrement=False, nullable=False),
#     )
#     op.add_column(
#         "transactions",
#         sa.Column(
#             "from_address", sa.VARCHAR(length=100), autoincrement=False, nullable=False
#         ),
#     )
#     op.drop_constraint(None, "transactions", type_="foreignkey")
#     op.drop_constraint(None, "transactions", type_="foreignkey")
#     op.drop_constraint(None, "transactions", type_="unique")
#     op.create_index(
#         op.f("ix_transactions_message_hash"),
#         "transactions",
#         ["message_hash"],
#         unique=True,
#     )
#     op.create_index(op.f("ix_transactions_hash"), "transactions", ["hash"], unique=True)
#     op.drop_column("transactions", "premium_months")
#     op.drop_column("transactions", "stars_amount")
#     op.drop_column("transactions", "reason")
#     op.drop_column("transactions", "ton_transaction_id")
#     op.drop_column("transactions", "recipient_username")
#     op.drop_column("transactions", "recipient")
#     op.drop_column("transactions", "amount")
#     op.drop_column("transactions", "user_id")
#     op.add_column(
#         "deposits",
#         sa.Column("transaction_id", sa.UUID(), autoincrement=False, nullable=True),
#     )
#     op.drop_constraint(None, "deposits", type_="foreignkey")
#     op.create_foreign_key(
#         op.f("payments_transaction_id_fkey"),
#         "deposits",
#         "transactions",
#         ["transaction_id"],
#         ["id"],
#     )
#     op.drop_constraint(None, "deposits", type_="unique")
#     op.drop_index(op.f("ix_deposits_created_at"), table_name="deposits")
#     op.create_unique_constraint(
#         op.f("payments_transaction_id_key"),
#         "deposits",
#         ["transaction_id"],
#         postgresql_nulls_not_distinct=False,
#     )
#     op.create_index(
#         op.f("ix_payments_created_at"), "deposits", ["created_at"], unique=False
#     )
#     op.drop_column("deposits", "ton_transaction_id")
#     op.create_table(
#         "fragment_transactions",
#         sa.Column("user_id", sa.BIGINT(), autoincrement=False, nullable=False),
#         sa.Column(
#             "amount",
#             sa.DOUBLE_PRECISION(precision=53),
#             autoincrement=False,
#             nullable=False,
#         ),
#         sa.Column("transaction_id", sa.UUID(), autoincrement=False, nullable=False),
#         sa.Column("reason", sa.VARCHAR(length=7), autoincrement=False, nullable=False),
#         sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
#         sa.Column(
#             "created_at",
#             postgresql.TIMESTAMP(timezone=True),
#             autoincrement=False,
#             nullable=False,
#         ),
#         sa.Column(
#             "modified_at",
#             postgresql.TIMESTAMP(timezone=True),
#             autoincrement=False,
#             nullable=True,
#         ),
#         sa.Column("recipient", sa.VARCHAR(), autoincrement=False, nullable=False),
#         sa.Column("premium_months", sa.INTEGER(), autoincrement=False, nullable=True),
#         sa.Column(
#             "recipient_username",
#             sa.VARCHAR(),
#             server_default=sa.text("''::character varying"),
#             autoincrement=False,
#             nullable=False,
#         ),
#         sa.Column("stars_amount", sa.INTEGER(), autoincrement=False, nullable=True),
#         sa.ForeignKeyConstraint(
#             ["transaction_id"],
#             ["transactions.id"],
#             name=op.f("fragment_transactions_transaction_id_fkey"),
#         ),
#         sa.ForeignKeyConstraint(
#             ["user_id"], ["users.id"], name=op.f("fragment_transactions_user_id_fkey")
#         ),
#         sa.PrimaryKeyConstraint("id", name=op.f("fragment_transactions_pkey")),
#         sa.UniqueConstraint(
#             "transaction_id",
#             name=op.f("fragment_transactions_transaction_id_key"),
#             postgresql_include=[],
#             postgresql_nulls_not_distinct=False,
#         ),
#     )
#     op.create_index(
#         op.f("ix_fragment_transactions_created_at"),
#         "fragment_transactions",
#         ["created_at"],
#         unique=False,
#     )
#     op.drop_index(
#         op.f("ix_ton_transactions_message_hash"), table_name="ton_transactions"
#     )
#     op.drop_index(op.f("ix_ton_transactions_hash"), table_name="ton_transactions")
#     op.drop_index(op.f("ix_ton_transactions_created_at"), table_name="ton_transactions")
#     op.drop_table("ton_transactions")
#     # ### end Alembic commands ###
