"""did smth

Revision ID: 4c83b885da60
Revises: 11a86c44c102
Create Date: 2026-05-14 12:20:28.737111

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4c83b885da60"
down_revision: str | Sequence[str] | None = "11a86c44c102"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "fragment_transactions", sa.Column("recipient", sa.String(), nullable=False)
    )
    op.add_column(
        "fragment_transactions", sa.Column("username", sa.String(), nullable=False)
    )
    op.add_column(
        "payments",
        sa.Column(
            "status",
            sa.Enum("pending", "completed", name="paymentstatus", native_enum=False),
            nullable=False,
        ),
    )
    op.alter_column(
        "payments", "transaction_id", existing_type=sa.UUID(), nullable=True
    )
    op.add_column(
        "transactions", sa.Column("hash", sa.String(length=64), nullable=True)
    )
    op.add_column(
        "transactions", sa.Column("from_address", sa.String(length=100), nullable=False)
    )
    op.add_column(
        "transactions", sa.Column("to_address", sa.String(length=100), nullable=False)
    )
    op.alter_column(
        "transactions",
        "nano_amount",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
    )
    op.create_index(op.f("ix_transactions_hash"), "transactions", ["hash"], unique=True)
    op.drop_column("transactions", "from_wallet")
    op.drop_column("transactions", "to_wallet")
    op.drop_column("transactions", "status")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions",
        sa.Column("status", sa.VARCHAR(length=9), autoincrement=False, nullable=False),
    )
    op.add_column(
        "transactions",
        sa.Column(
            "to_wallet", sa.VARCHAR(length=48), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "transactions",
        sa.Column(
            "from_wallet", sa.VARCHAR(length=48), autoincrement=False, nullable=False
        ),
    )
    op.drop_index(op.f("ix_transactions_hash"), table_name="transactions")
    op.alter_column(
        "transactions",
        "nano_amount",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.drop_column("transactions", "to_address")
    op.drop_column("transactions", "from_address")
    op.drop_column("transactions", "hash")
    op.alter_column(
        "payments", "transaction_id", existing_type=sa.UUID(), nullable=False
    )
    op.drop_column("payments", "status")
    op.drop_column("fragment_transactions", "username")
    op.drop_column("fragment_transactions", "recipient")
    # ### end Alembic commands ###
