"""fragtrans rework

Revision ID: 0f3d06b61184
Revises: 48661a0dd21c
Create Date: 2026-05-17 17:07:52.041131

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0f3d06b61184"
down_revision: str | Sequence[str] | None = "48661a0dd21c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "fragment_transactions",
        sa.Column("recipient_username", sa.String(), nullable=False, server_default=""),
    )
    op.add_column(
        "fragment_transactions", sa.Column("stars_amount", sa.Integer(), nullable=True)
    )
    op.drop_column("fragment_transactions", "star_amount")
    op.drop_column("fragment_transactions", "username")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "fragment_transactions",
        sa.Column("username", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "fragment_transactions",
        sa.Column("star_amount", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_column("fragment_transactions", "stars_amount")
    op.drop_column("fragment_transactions", "recipient_username")
    # ### end Alembic commands ###
