"""remove tx_hash added message_hash

Revision ID: cff64de98a84
Revises: a82a1107eabf
Create Date: 2026-05-06 13:10:05.485858

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cff64de98a84"
down_revision: str | Sequence[str] | None = "a82a1107eabf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions", sa.Column("message_hash", sa.String(length=64), nullable=True)
    )
    op.alter_column(
        "transactions",
        "recipient",
        existing_type=sa.VARCHAR(length=255),
        nullable=False,
    )
    op.drop_index(op.f("ix_transactions_tx_hash"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_updated_at"), table_name="transactions")
    op.create_index(
        op.f("ix_transactions_message_hash"),
        "transactions",
        ["message_hash"],
        unique=False,
    )
    op.drop_column("transactions", "stars_quantity")
    op.drop_column("transactions", "tx_hash")
    op.drop_index(op.f("ix_user_sessions_updated_at"), table_name="user_sessions")
    op.drop_index(op.f("ix_users_updated_at"), table_name="users")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_users_updated_at"), "users", ["updated_at"], unique=False)
    op.create_index(
        op.f("ix_user_sessions_updated_at"),
        "user_sessions",
        ["updated_at"],
        unique=False,
    )
    op.add_column(
        "transactions",
        sa.Column("tx_hash", sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    )
    op.add_column(
        "transactions",
        sa.Column("stars_quantity", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_index(op.f("ix_transactions_message_hash"), table_name="transactions")
    op.create_index(
        op.f("ix_transactions_updated_at"), "transactions", ["updated_at"], unique=False
    )
    op.create_index(
        op.f("ix_transactions_tx_hash"), "transactions", ["tx_hash"], unique=False
    )
    op.alter_column(
        "transactions", "recipient", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.drop_column("transactions", "message_hash")
    # ### end Alembic commands ###
