"""telegram_logs_source

Revision ID: fccb267549ff
Revises: a3a46bbb7cd5
Create Date: 2026-06-09 07:53:33.231831

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fccb267549ff"
down_revision: str | Sequence[str] | None = "a3a46bbb7cd5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "telegram_logs_sources",
        sa.Column("chat_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chat_id"),
        sa.UniqueConstraint("chat_id", "user_id"),
    )
    op.create_index(
        op.f("ix_telegram_logs_sources_created_at"),
        "telegram_logs_sources",
        ["created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_telegram_logs_sources_created_at"), table_name="telegram_logs_sources"
    )
    op.drop_table("telegram_logs_sources")
    # ### end Alembic commands ###
