"""api_tokens

Revision ID: a3a46bbb7cd5
Revises: 0f3d06b61184
Create Date: 2026-06-06 17:25:37.571983

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a3a46bbb7cd5"
down_revision: str | Sequence[str] | None = "0f3d06b61184"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_tokens",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    op.create_index(
        op.f("ix_api_tokens_created_at"), "api_tokens", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_api_tokens_expires_at"), "api_tokens", ["expires_at"], unique=False
    )
    op.drop_constraint(op.f("users_api_key_key"), "users", type_="unique")
    op.drop_column("users", "api_key")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("api_key", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.create_unique_constraint(
        op.f("users_api_key_key"),
        "users",
        ["api_key"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_index(op.f("ix_api_tokens_expires_at"), table_name="api_tokens")
    op.drop_index(op.f("ix_api_tokens_created_at"), table_name="api_tokens")
    op.drop_table("api_tokens")
    # ### end Alembic commands ###
