"""star_amount and premium_months

Revision ID: 48661a0dd21c
Revises: 4c83b885da60
Create Date: 2026-05-14 21:24:47.465270

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "48661a0dd21c"
down_revision: str | Sequence[str] | None = "4c83b885da60"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "fragment_transactions", sa.Column("star_amount", sa.Integer(), nullable=True)
    )
    op.add_column(
        "fragment_transactions",
        sa.Column("premium_months", sa.Integer(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("fragment_transactions", "premium_months")
    op.drop_column("fragment_transactions", "star_amount")
    # ### end Alembic commands ###
