"""fix_for_the_transaction_refactor_1

Revision ID: baba3f4c466e
Revises: 9997c8bcf3d5
Create Date: 2026-06-20 13:38:35.616876

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "baba3f4c466e"
down_revision: str | Sequence[str] | None = "9997c8bcf3d5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # --- payments -> deposits

    op.execute("ALTER INDEX ix_payments_created_at RENAME TO ix_deposits_created_at")
    op.execute("ALTER INDEX payments_pkey RENAME TO deposits_pkey")
    op.execute("ALTER INDEX payments_hash_key RENAME TO deposits_hash_key")
    op.execute(
        "ALTER INDEX payments_transaction_id_key RENAME TO deposits_transaction_id_key"
    )

    op.rename_table("payments", "deposits")

    # --- transactions -> ton_transactions

    op.execute("ALTER INDEX ix_transactions_hash RENAME TO ix_ton_transactions_hash")
    op.execute(
        "ALTER INDEX ix_transactions_message_hash RENAME TO ix_ton_transactions_message_hash"
    )
    op.execute(
        "ALTER INDEX ix_transactions_created_at RENAME TO ix_ton_transactions_created_at"
    )
    op.execute("ALTER INDEX transactions_pkey RENAME TO ton_transactions_pkey")

    op.rename_table("transactions", "ton_transactions")

    # --- NOTE: fragment_transactions -> transactions in the next one.


def downgrade() -> None:
    # TODO: ...
    pass


# def upgrade() -> None:
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.create_table(
#         "ton_transactions",
#         sa.Column("nano_amount", sa.BigInteger(), nullable=False),
#         sa.Column("hash", sa.String(length=64), nullable=True),
#         sa.Column("message_hash", sa.String(length=64), nullable=True),
#         sa.Column("from_address", sa.String(length=100), nullable=False),
#         sa.Column("to_address", sa.String(length=100), nullable=False),
#         sa.Column("id", sa.Uuid(), nullable=False),
#         sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
#         sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
#         sa.PrimaryKeyConstraint("id"),
#     )
#     op.create_index(
#         op.f("ix_ton_transactions_created_at"),
#         "ton_transactions",
#         ["created_at"],
#         unique=False,
#     )
#     op.create_index(
#         op.f("ix_ton_transactions_hash"), "ton_transactions", ["hash"], unique=True
#     )
#     op.create_index(
#         op.f("ix_ton_transactions_message_hash"),
#         "ton_transactions",
#         ["message_hash"],
#         unique=True,
#     )
#     op.create_table(
#         "deposits",
#         sa.Column("user_id", sa.BigInteger(), nullable=False),
#         sa.Column("amount", sa.Float(), nullable=False),
#         sa.Column("hash", sa.String(), nullable=False),
#         sa.Column("ton_transaction_id", sa.Uuid(), nullable=True),
#         sa.Column(
#             "status",
#             sa.Enum("pending", "completed", name="depositstatus", native_enum=False),
#             nullable=False,
#         ),
#         sa.Column("id", sa.Uuid(), nullable=False),
#         sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
#         sa.Column("modified_at", sa.TIMESTAMP(timezone=True), nullable=True),
#         sa.ForeignKeyConstraint(
#             ["ton_transaction_id"],
#             ["ton_transactions.id"],
#         ),
#         sa.ForeignKeyConstraint(
#             ["user_id"],
#             ["users.id"],
#         ),
#         sa.PrimaryKeyConstraint("id"),
#         sa.UniqueConstraint("hash"),
#         sa.UniqueConstraint("ton_transaction_id"),
#     )
#     op.create_index(
#         op.f("ix_deposits_created_at"), "deposits", ["created_at"], unique=False
#     )
#     op.drop_index(
#         op.f("ix_fragment_transactions_created_at"), table_name="fragment_transactions"
#     )
#     op.drop_table("fragment_transactions")
#     op.drop_index(op.f("ix_deposits_created_at"), table_name="payments")
#     op.drop_table("payments")
#     op.add_column("transactions", sa.Column("user_id", sa.BigInteger(), nullable=False))
#     op.add_column("transactions", sa.Column("amount", sa.Float(), nullable=False))
#     op.add_column("transactions", sa.Column("recipient", sa.String(), nullable=False))
#     op.add_column(
#         "transactions", sa.Column("recipient_username", sa.String(), nullable=False)
#     )
#     op.add_column(
#         "transactions", sa.Column("ton_transaction_id", sa.Uuid(), nullable=False)
#     )
#     op.add_column(
#         "transactions",
#         sa.Column(
#             "reason",
#             sa.Enum("premium", "stars", name="transactionreason", native_enum=False),
#             nullable=False,
#         ),
#     )
#     op.add_column(
#         "transactions", sa.Column("stars_amount", sa.Integer(), nullable=True)
#     )
#     op.add_column(
#         "transactions", sa.Column("premium_months", sa.Integer(), nullable=True)
#     )
#     op.drop_index(op.f("ix_transactions_hash"), table_name="transactions")
#     op.drop_index(op.f("ix_transactions_message_hash"), table_name="transactions")
#     op.create_unique_constraint(None, "transactions", ["ton_transaction_id"])
#     op.create_foreign_key(
#         None, "transactions", "ton_transactions", ["ton_transaction_id"], ["id"]
#     )
#     op.create_foreign_key(None, "transactions", "users", ["user_id"], ["id"])
#     op.drop_column("transactions", "nano_amount")
#     op.drop_column("transactions", "to_address")
#     op.drop_column("transactions", "hash")
#     op.drop_column("transactions", "message_hash")
#     op.drop_column("transactions", "from_address")
#     # ### end Alembic commands ###
#
#
# def downgrade() -> None:
#     """Downgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.add_column(
#         "transactions",
#         sa.Column(
#             "from_address", sa.VARCHAR(length=100), autoincrement=False, nullable=False
#         ),
#     )
#     op.add_column(
#         "transactions",
#         sa.Column(
#             "message_hash", sa.VARCHAR(length=64), autoincrement=False, nullable=True
#         ),
#     )
#     op.add_column(
#         "transactions",
#         sa.Column("hash", sa.VARCHAR(length=64), autoincrement=False, nullable=True),
#     )
#     op.add_column(
#         "transactions",
#         sa.Column(
#             "to_address", sa.VARCHAR(length=100), autoincrement=False, nullable=False
#         ),
#     )
#     op.add_column(
#         "transactions",
#         sa.Column("nano_amount", sa.BIGINT(), autoincrement=False, nullable=False),
#     )
#     op.drop_constraint(None, "transactions", type_="foreignkey")
#     op.drop_constraint(None, "transactions", type_="foreignkey")
#     op.drop_constraint(None, "transactions", type_="unique")
#     op.create_index(
#         op.f("ix_transactions_message_hash"),
#         "transactions",
#         ["message_hash"],
#         unique=True,
#     )
#     op.create_index(op.f("ix_transactions_hash"), "transactions", ["hash"], unique=True)
#     op.drop_column("transactions", "premium_months")
#     op.drop_column("transactions", "stars_amount")
#     op.drop_column("transactions", "reason")
#     op.drop_column("transactions", "ton_transaction_id")
#     op.drop_column("transactions", "recipient_username")
#     op.drop_column("transactions", "recipient")
#     op.drop_column("transactions", "amount")
#     op.drop_column("transactions", "user_id")
#     op.create_table(
#         "payments",
#         sa.Column("user_id", sa.BIGINT(), autoincrement=False, nullable=False),
#         sa.Column(
#             "amount",
#             sa.DOUBLE_PRECISION(precision=53),
#             autoincrement=False,
#             nullable=False,
#         ),
#         sa.Column("hash", sa.VARCHAR(), autoincrement=False, nullable=False),
#         sa.Column("transaction_id", sa.UUID(), autoincrement=False, nullable=True),
#         sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
#         sa.Column(
#             "created_at",
#             postgresql.TIMESTAMP(timezone=True),
#             autoincrement=False,
#             nullable=False,
#         ),
#         sa.Column(
#             "modified_at",
#             postgresql.TIMESTAMP(timezone=True),
#             autoincrement=False,
#             nullable=True,
#         ),
#         sa.Column("status", sa.VARCHAR(length=9), autoincrement=False, nullable=False),
#         sa.ForeignKeyConstraint(
#             ["transaction_id"],
#             ["transactions.id"],
#             name=op.f("payments_transaction_id_fkey"),
#         ),
#         sa.ForeignKeyConstraint(
#             ["user_id"], ["users.id"], name=op.f("payments_user_id_fkey")
#         ),
#         sa.PrimaryKeyConstraint("id", name=op.f("payments_pkey")),
#         sa.UniqueConstraint(
#             "hash",
#             name=op.f("payments_hash_key"),
#             postgresql_include=[],
#             postgresql_nulls_not_distinct=False,
#         ),
#         sa.UniqueConstraint(
#             "transaction_id",
#             name=op.f("payments_transaction_id_key"),
#             postgresql_include=[],
#             postgresql_nulls_not_distinct=False,
#         ),
#     )
#     op.create_index(
#         op.f("ix_deposits_created_at"), "payments", ["created_at"], unique=False
#     )
#     op.create_table(
#         "fragment_transactions",
#         sa.Column("user_id", sa.BIGINT(), autoincrement=False, nullable=False),
#         sa.Column(
#             "amount",
#             sa.DOUBLE_PRECISION(precision=53),
#             autoincrement=False,
#             nullable=False,
#         ),
#         sa.Column("transaction_id", sa.UUID(), autoincrement=False, nullable=False),
#         sa.Column("reason", sa.VARCHAR(length=7), autoincrement=False, nullable=False),
#         sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
#         sa.Column(
#             "created_at",
#             postgresql.TIMESTAMP(timezone=True),
#             autoincrement=False,
#             nullable=False,
#         ),
#         sa.Column(
#             "modified_at",
#             postgresql.TIMESTAMP(timezone=True),
#             autoincrement=False,
#             nullable=True,
#         ),
#         sa.Column("recipient", sa.VARCHAR(), autoincrement=False, nullable=False),
#         sa.Column("premium_months", sa.INTEGER(), autoincrement=False, nullable=True),
#         sa.Column(
#             "recipient_username",
#             sa.VARCHAR(),
#             server_default=sa.text("''::character varying"),
#             autoincrement=False,
#             nullable=False,
#         ),
#         sa.Column("stars_amount", sa.INTEGER(), autoincrement=False, nullable=True),
#         sa.ForeignKeyConstraint(
#             ["transaction_id"],
#             ["transactions.id"],
#             name=op.f("fragment_transactions_transaction_id_fkey"),
#         ),
#         sa.ForeignKeyConstraint(
#             ["user_id"], ["users.id"], name=op.f("fragment_transactions_user_id_fkey")
#         ),
#         sa.PrimaryKeyConstraint("id", name=op.f("fragment_transactions_pkey")),
#         sa.UniqueConstraint(
#             "transaction_id",
#             name=op.f("fragment_transactions_transaction_id_key"),
#             postgresql_include=[],
#             postgresql_nulls_not_distinct=False,
#         ),
#     )
#     op.create_index(
#         op.f("ix_fragment_transactions_created_at"),
#         "fragment_transactions",
#         ["created_at"],
#         unique=False,
#     )
#     op.drop_index(op.f("ix_deposits_created_at"), table_name="deposits")
#     op.drop_table("deposits")
#     op.drop_index(
#         op.f("ix_ton_transactions_message_hash"), table_name="ton_transactions"
#     )
#     op.drop_index(op.f("ix_ton_transactions_hash"), table_name="ton_transactions")
#     op.drop_index(op.f("ix_ton_transactions_created_at"), table_name="ton_transactions")
#     op.drop_table("ton_transactions")
#     # ### end Alembic commands ###
