"""just_checking

Revision ID: e80a3b7c4637
Revises: f8ab285d7b48
Create Date: 2026-07-10 14:38:22.648479

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e80a3b7c4637"
down_revision: str | Sequence[str] | None = "f8ab285d7b48"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # TODO: Rename index to ad ix_ at the start.

    # # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f("transactions_created_at"), table_name="transactions")
    # op.create_index(
    #     op.f("ix_transactions_created_at"), "transactions", ["created_at"], unique=False
    # )
    # # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # TODO: Rename index to ad ix_ at the start. downgrade.

    # # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f("ix_transactions_created_at"), table_name="transactions")
    # op.create_index(
    #     op.f("transactions_created_at"), "transactions", ["created_at"], unique=False
    # )
    # # ### end Alembic commands ###
